server:
  port: 20002
  error:
    include-message: always

spring:
  application:
    name: coupon-calculate-serv
  cloud:
    nacos:
      # nacos 服务发现
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        namespace: 947a7b68-c711-470b-bc3c-9a337001dc16
        group: COUPON
        metadata:
          mydata: coupon-template-serv
          traffic-version: blue