server:
  port: 20001
  error:
    include-message: always

spring:
  application:
    name: coupon-calculate-serv
  cloud:
    nacos:
      # nacos 服务发现
      discovery:
        enabled: true
        server-addr: 192.168.44.208:8848
        namespace: 947a7b68-c711-470b-bc3c-9a337001dc16
        metadata:
          mydata: coupon-template-serv